name: Test
'on':
  push:
    branches:
      - main
jobs:
  test:
  name: 'Node v${{ matrix.node }}'
  runs-on: 'ubuntu-latest'
  strategy:
    matrix:
      node:
        - 12
        - 14
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '${{ matrix.node }}'
    - uses: actions/checkout@v2
    - name: 'Cache node_modules'
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os}}-node-v${{ matrix.node }}-${{ hashFiles('**/pachage-lock.json') }}
        restore-keys: |
          - ${{ runner.os}}-node-v${{ matrix.node }}-
    - name: 'Instalando dependencias'
      run: npm install
    - name: 'Ejecutando test del proyecto'
      run: npm test